import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StoreProvider } from '@/store/StoreProvider'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang='en'>
        <body className={`${inter.className} p-2`}>
          <h1 className='text-2xl font-bold'>Next 13 + Redux Toolkit</h1>
          {children}
        </body>
      </html>
    </StoreProvider>
  )
}
